with tbrct_source as (
        select braco,
               spras,
               vtext,
               mandt
          from {{ ref('DLV_STAGING_TBRCT') }}
       ),
       prj_kna1 as (
        select mandt,
               kunnr,
               land1,
               name1,
               name2,
               ort01,
               pstlz,
               regio,
               sortl,
               stras,
               telf1,
               telfx,
               xcpdk,
               adrnr,
               anred,
               aufsd,
               bahne,
               bahns,
               erdat,
               ernam,
               exabl,
               faksd,
               knrza,
               ktokd,
               kukla,
               lifnr,
               lifsd,
               locco,
               loevm,
               name3,
               name4,
               ort02,
               pfach,
               pstl2,
               counc,
               cityc,
               rpmkr,
               sperr,
               spras,
               stcd1,
               stcd2,
               stkza,
               stkzu,
               telf2,
               lzone,
               stceg,
               bran1,
               bran2,
               bran3,
               bran4,
               bran5,
               katr1,
               katr2,
               katr3,
               katr4,
               katr5,
               katr6,
               katr7,
               katr8,
               katr9,
               katr10,
               txjcd,
               werks,
               hzuor,
               sperz,
               fityp,
               stcdt,
               stcd3,
               stcd4,
               stcd5,
               cassd,
               knurl,
               j_1kftbus,
               j_1kftind,
               nodel,
               indtyp,
               tdt,
               comsize,
               brsch,
               zzxgn
          from {{ ref('DLV_STAGING_KNA1') }}
       ),
       p_industrycode5text as (
        select mandt,
               spras,
               braco,
               vtext
          from {{ ref('DLV_STAGING_TBRCT') }}
       ),
       p_industrycode1text as (
        select mandt,
               spras,
               braco,
               vtext
          from {{ ref('DLV_STAGING_TBRCT') }}
       ),
       join_4 as (
        select prj_kna1.mandt as mandt,
               prj_kna1.kunnr as kunnr,
               prj_kna1.land1 as land1,
               prj_kna1.name1 as name1,
               prj_kna1.name2 as name2,
               prj_kna1.ort01 as ort01,
               prj_kna1.pstlz as pstlz,
               prj_kna1.regio as regio,
               prj_kna1.sortl as sortl,
               prj_kna1.stras as stras,
               prj_kna1.telf1 as telf1,
               prj_kna1.telfx as telfx,
               prj_kna1.xcpdk as xcpdk,
               prj_kna1.adrnr as adrnr,
               prj_kna1.anred as anred,
               prj_kna1.aufsd as aufsd,
               prj_kna1.bahne as bahne,
               prj_kna1.bahns as bahns,
               prj_kna1.brsch as brsch,
               prj_kna1.erdat as erdat,
               prj_kna1.ernam as ernam,
               prj_kna1.exabl as exabl,
               prj_kna1.faksd as faksd,
               prj_kna1.knrza as knrza,
               prj_kna1.ktokd as ktokd,
               prj_kna1.kukla as kukla,
               prj_kna1.lifnr as lifnr,
               prj_kna1.lifsd as lifsd,
               prj_kna1.locco as locco,
               prj_kna1.loevm as loevm,
               prj_kna1.name3 as name3,
               prj_kna1.name4 as name4,
               prj_kna1.ort02 as ort02,
               prj_kna1.pfach as pfach,
               prj_kna1.pstl2 as pstl2,
               prj_kna1.counc as counc,
               prj_kna1.cityc as cityc,
               prj_kna1.rpmkr as rpmkr,
               prj_kna1.sperr as sperr,
               prj_kna1.spras as spras,
               prj_kna1.stcd1 as stcd1,
               prj_kna1.stcd2 as stcd2,
               prj_kna1.stkza as stkza,
               prj_kna1.stkzu as stkzu,
               prj_kna1.telf2 as telf2,
               prj_kna1.lzone as lzone,
               prj_kna1.stceg as stceg,
               prj_kna1.bran1 as bran1,
               prj_kna1.bran2 as bran2,
               prj_kna1.bran3 as bran3,
               prj_kna1.bran4 as bran4,
               prj_kna1.bran5 as bran5,
               prj_kna1.katr1 as katr1,
               prj_kna1.katr2 as katr2,
               prj_kna1.katr3 as katr3,
               prj_kna1.katr4 as katr4,
               prj_kna1.katr5 as katr5,
               prj_kna1.katr6 as katr6,
               prj_kna1.katr7 as katr7,
               prj_kna1.katr8 as katr8,
               prj_kna1.katr9 as katr9,
               prj_kna1.katr10 as katr10,
               prj_kna1.txjcd as txjcd,
               prj_kna1.werks as werks,
               prj_kna1.hzuor as hzuor,
               prj_kna1.sperz as sperz,
               prj_kna1.fityp as fityp,
               prj_kna1.stcdt as stcdt,
               prj_kna1.stcd3 as stcd3,
               prj_kna1.stcd4 as stcd4,
               prj_kna1.stcd5 as stcd5,
               prj_kna1.cassd as cassd,
               prj_kna1.knurl as knurl,
               prj_kna1.j_1kftbus as j_1kftbus,
               prj_kna1.j_1kftind as j_1kftind,
               prj_kna1.nodel as nodel,
               prj_kna1.indtyp as indtyp,
               prj_kna1.tdt as tdt,
               prj_kna1.comsize as comsize,
               prj_kna1.zzxgn as zzxgn,
               p_industrycode1text.vtext as tbrct_bran1_vtext
          from prj_kna1
          left outer join p_industrycode1text
            on prj_kna1.bran1 = p_industrycode1text.braco
       ),
       p_industrycode2text as (
        select mandt,
               spras,
               braco,
               vtext
          from {{ ref('DLV_STAGING_TBRCT') }}
       ),
       join_3 as (
        select join_4.mandt as mandt,
               join_4.kunnr as kunnr,
               join_4.land1 as land1,
               join_4.name1 as name1,
               join_4.name2 as name2,
               join_4.ort01 as ort01,
               join_4.pstlz as pstlz,
               join_4.regio as regio,
               join_4.sortl as sortl,
               join_4.stras as stras,
               join_4.telf1 as telf1,
               join_4.telfx as telfx,
               join_4.xcpdk as xcpdk,
               join_4.adrnr as adrnr,
               join_4.anred as anred,
               join_4.aufsd as aufsd,
               join_4.bahne as bahne,
               join_4.bahns as bahns,
               join_4.brsch as brsch,
               join_4.erdat as erdat,
               join_4.ernam as ernam,
               join_4.exabl as exabl,
               join_4.faksd as faksd,
               join_4.knrza as knrza,
               join_4.ktokd as ktokd,
               join_4.kukla as kukla,
               join_4.lifnr as lifnr,
               join_4.lifsd as lifsd,
               join_4.locco as locco,
               join_4.loevm as loevm,
               join_4.name3 as name3,
               join_4.name4 as name4,
               join_4.ort02 as ort02,
               join_4.pfach as pfach,
               join_4.pstl2 as pstl2,
               join_4.counc as counc,
               join_4.cityc as cityc,
               join_4.rpmkr as rpmkr,
               join_4.sperr as sperr,
               join_4.spras as spras,
               join_4.stcd1 as stcd1,
               join_4.stcd2 as stcd2,
               join_4.stkza as stkza,
               join_4.stkzu as stkzu,
               join_4.telf2 as telf2,
               join_4.lzone as lzone,
               join_4.stceg as stceg,
               join_4.bran1 as bran1,
               join_4.bran2 as bran2,
               join_4.bran3 as bran3,
               join_4.bran4 as bran4,
               join_4.bran5 as bran5,
               join_4.katr1 as katr1,
               join_4.katr2 as katr2,
               join_4.katr3 as katr3,
               join_4.katr4 as katr4,
               join_4.katr5 as katr5,
               join_4.katr6 as katr6,
               join_4.katr7 as katr7,
               join_4.katr8 as katr8,
               join_4.katr9 as katr9,
               join_4.katr10 as katr10,
               join_4.txjcd as txjcd,
               join_4.werks as werks,
               join_4.hzuor as hzuor,
               join_4.sperz as sperz,
               join_4.fityp as fityp,
               join_4.stcdt as stcdt,
               join_4.stcd3 as stcd3,
               join_4.stcd4 as stcd4,
               join_4.stcd5 as stcd5,
               join_4.cassd as cassd,
               join_4.knurl as knurl,
               join_4.j_1kftbus as j_1kftbus,
               join_4.j_1kftind as j_1kftind,
               join_4.nodel as nodel,
               join_4.indtyp as indtyp,
               join_4.tdt as tdt,
               join_4.comsize as comsize,
               join_4.zzxgn as zzxgn,
               join_4.tbrct_bran1_vtext as tbrct_bran1_vtext,
               p_industrycode2text.vtext as tbrct_bran2_vtext
          from join_4
          left outer join p_industrycode2text
            on join_4.bran2 = p_industrycode2text.braco
       ),
       p_industrycode3text as (
        select mandt,
               spras,
               braco,
               vtext
          from {{ ref('DLV_STAGING_TBRCT') }}
       ),
       join_2 as (
        select join_3.mandt as mandt,
               join_3.kunnr as kunnr,
               join_3.land1 as land1,
               join_3.name1 as name1,
               join_3.name2 as name2,
               join_3.ort01 as ort01,
               join_3.pstlz as pstlz,
               join_3.regio as regio,
               join_3.sortl as sortl,
               join_3.stras as stras,
               join_3.telf1 as telf1,
               join_3.telfx as telfx,
               join_3.xcpdk as xcpdk,
               join_3.adrnr as adrnr,
               join_3.anred as anred,
               join_3.aufsd as aufsd,
               join_3.bahne as bahne,
               join_3.bahns as bahns,
               join_3.brsch as brsch,
               join_3.erdat as erdat,
               join_3.ernam as ernam,
               join_3.exabl as exabl,
               join_3.faksd as faksd,
               join_3.knrza as knrza,
               join_3.ktokd as ktokd,
               join_3.kukla as kukla,
               join_3.lifnr as lifnr,
               join_3.lifsd as lifsd,
               join_3.locco as locco,
               join_3.loevm as loevm,
               join_3.name3 as name3,
               join_3.name4 as name4,
               join_3.ort02 as ort02,
               join_3.pfach as pfach,
               join_3.pstl2 as pstl2,
               join_3.counc as counc,
               join_3.cityc as cityc,
               join_3.rpmkr as rpmkr,
               join_3.sperr as sperr,
               join_3.spras as spras,
               join_3.stcd1 as stcd1,
               join_3.stcd2 as stcd2,
               join_3.stkza as stkza,
               join_3.stkzu as stkzu,
               join_3.telf2 as telf2,
               join_3.lzone as lzone,
               join_3.stceg as stceg,
               join_3.bran1 as bran1,
               join_3.bran2 as bran2,
               join_3.bran3 as bran3,
               join_3.bran4 as bran4,
               join_3.bran5 as bran5,
               join_3.katr1 as katr1,
               join_3.katr2 as katr2,
               join_3.katr3 as katr3,
               join_3.katr4 as katr4,
               join_3.katr5 as katr5,
               join_3.katr6 as katr6,
               join_3.katr7 as katr7,
               join_3.katr8 as katr8,
               join_3.katr9 as katr9,
               join_3.katr10 as katr10,
               join_3.txjcd as txjcd,
               join_3.werks as werks,
               join_3.hzuor as hzuor,
               join_3.sperz as sperz,
               join_3.fityp as fityp,
               join_3.stcdt as stcdt,
               join_3.stcd3 as stcd3,
               join_3.stcd4 as stcd4,
               join_3.stcd5 as stcd5,
               join_3.cassd as cassd,
               join_3.knurl as knurl,
               join_3.j_1kftbus as j_1kftbus,
               join_3.j_1kftind as j_1kftind,
               join_3.nodel as nodel,
               join_3.indtyp as indtyp,
               join_3.tdt as tdt,
               join_3.comsize as comsize,
               join_3.zzxgn as zzxgn,
               join_3.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_3.tbrct_bran2_vtext as tbrct_bran2_vtext,
               p_industrycode3text.vtext as tbrct_bran3_vtext
          from join_3
          left outer join p_industrycode3text
            on join_3.bran3 = p_industrycode3text.braco
       ),
       p_industrycode4text as (
        select mandt,
               spras,
               braco,
               vtext
          from {{ ref('DLV_STAGING_TBRCT') }}
       ),
       join_1 as (
        select join_2.mandt as mandt,
               join_2.kunnr as kunnr,
               join_2.land1 as land1,
               join_2.name1 as name1,
               join_2.name2 as name2,
               join_2.ort01 as ort01,
               join_2.pstlz as pstlz,
               join_2.regio as regio,
               join_2.sortl as sortl,
               join_2.stras as stras,
               join_2.telf1 as telf1,
               join_2.telfx as telfx,
               join_2.xcpdk as xcpdk,
               join_2.adrnr as adrnr,
               join_2.anred as anred,
               join_2.aufsd as aufsd,
               join_2.bahne as bahne,
               join_2.bahns as bahns,
               join_2.brsch as brsch,
               join_2.erdat as erdat,
               join_2.ernam as ernam,
               join_2.exabl as exabl,
               join_2.faksd as faksd,
               join_2.knrza as knrza,
               join_2.ktokd as ktokd,
               join_2.kukla as kukla,
               join_2.lifnr as lifnr,
               join_2.lifsd as lifsd,
               join_2.locco as locco,
               join_2.loevm as loevm,
               join_2.name3 as name3,
               join_2.name4 as name4,
               join_2.ort02 as ort02,
               join_2.pfach as pfach,
               join_2.pstl2 as pstl2,
               join_2.counc as counc,
               join_2.cityc as cityc,
               join_2.rpmkr as rpmkr,
               join_2.sperr as sperr,
               join_2.spras as spras,
               join_2.stcd1 as stcd1,
               join_2.stcd2 as stcd2,
               join_2.stkza as stkza,
               join_2.stkzu as stkzu,
               join_2.telf2 as telf2,
               join_2.lzone as lzone,
               join_2.stceg as stceg,
               join_2.bran1 as bran1,
               join_2.bran2 as bran2,
               join_2.bran3 as bran3,
               join_2.bran4 as bran4,
               join_2.bran5 as bran5,
               join_2.katr1 as katr1,
               join_2.katr2 as katr2,
               join_2.katr3 as katr3,
               join_2.katr4 as katr4,
               join_2.katr5 as katr5,
               join_2.katr6 as katr6,
               join_2.katr7 as katr7,
               join_2.katr8 as katr8,
               join_2.katr9 as katr9,
               join_2.katr10 as katr10,
               join_2.txjcd as txjcd,
               join_2.werks as werks,
               join_2.hzuor as hzuor,
               join_2.sperz as sperz,
               join_2.fityp as fityp,
               join_2.stcdt as stcdt,
               join_2.stcd3 as stcd3,
               join_2.stcd4 as stcd4,
               join_2.stcd5 as stcd5,
               join_2.cassd as cassd,
               join_2.knurl as knurl,
               join_2.j_1kftbus as j_1kftbus,
               join_2.j_1kftind as j_1kftind,
               join_2.nodel as nodel,
               join_2.indtyp as indtyp,
               join_2.tdt as tdt,
               join_2.comsize as comsize,
               join_2.zzxgn as zzxgn,
               join_2.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_2.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_2.tbrct_bran3_vtext as tbrct_bran3_vtext,
               p_industrycode4text.vtext as tbrct_bran4_vtext
          from join_2
          left outer join p_industrycode4text
            on join_2.bran4 = p_industrycode4text.braco
       ),
       p_citytxt as (
        select mandt,
               spras,
               land1,
               regio,
               cityc,
               bezei
          from {{ ref('DLV_STAGING_T005H') }}
       ),
       join_5 as (
        select join_1.mandt as mandt,
               join_1.kunnr as kunnr,
               join_1.land1 as land1,
               join_1.name1 as name1,
               join_1.name2 as name2,
               join_1.ort01 as ort01,
               join_1.pstlz as pstlz,
               join_1.regio as regio,
               join_1.sortl as sortl,
               join_1.stras as stras,
               join_1.telf1 as telf1,
               join_1.telfx as telfx,
               join_1.xcpdk as xcpdk,
               join_1.adrnr as adrnr,
               join_1.anred as anred,
               join_1.aufsd as aufsd,
               join_1.bahne as bahne,
               join_1.bahns as bahns,
               join_1.brsch as brsch,
               join_1.erdat as erdat,
               join_1.ernam as ernam,
               join_1.exabl as exabl,
               join_1.faksd as faksd,
               join_1.knrza as knrza,
               join_1.ktokd as ktokd,
               join_1.kukla as kukla,
               join_1.lifnr as lifnr,
               join_1.lifsd as lifsd,
               join_1.locco as locco,
               join_1.loevm as loevm,
               join_1.name3 as name3,
               join_1.name4 as name4,
               join_1.ort02 as ort02,
               join_1.pfach as pfach,
               join_1.pstl2 as pstl2,
               join_1.counc as counc,
               join_1.cityc as cityc,
               join_1.rpmkr as rpmkr,
               join_1.sperr as sperr,
               join_1.spras as spras,
               join_1.stcd1 as stcd1,
               join_1.stcd2 as stcd2,
               join_1.stkza as stkza,
               join_1.stkzu as stkzu,
               join_1.telf2 as telf2,
               join_1.lzone as lzone,
               join_1.stceg as stceg,
               join_1.bran1 as bran1,
               join_1.bran2 as bran2,
               join_1.bran3 as bran3,
               join_1.bran4 as bran4,
               join_1.bran5 as bran5,
               join_1.katr1 as katr1,
               join_1.katr2 as katr2,
               join_1.katr3 as katr3,
               join_1.katr4 as katr4,
               join_1.katr5 as katr5,
               join_1.katr6 as katr6,
               join_1.katr7 as katr7,
               join_1.katr8 as katr8,
               join_1.katr9 as katr9,
               join_1.katr10 as katr10,
               join_1.txjcd as txjcd,
               join_1.werks as werks,
               join_1.hzuor as hzuor,
               join_1.sperz as sperz,
               join_1.fityp as fityp,
               join_1.stcdt as stcdt,
               join_1.stcd3 as stcd3,
               join_1.stcd4 as stcd4,
               join_1.stcd5 as stcd5,
               join_1.cassd as cassd,
               join_1.knurl as knurl,
               join_1.j_1kftbus as j_1kftbus,
               join_1.j_1kftind as j_1kftind,
               join_1.nodel as nodel,
               join_1.indtyp as indtyp,
               join_1.tdt as tdt,
               join_1.comsize as comsize,
               join_1.zzxgn as zzxgn,
               join_1.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_1.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_1.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_1.tbrct_bran4_vtext as tbrct_bran4_vtext,
               p_citytxt.bezei as t005h_bezei
          from join_1
          left outer join p_citytxt
            on join_1.land1 = p_citytxt.land1
           and join_1.regio = p_citytxt.regio
           and join_1.cityc = p_citytxt.cityc
       ),
       p_countytxt as (
        select mandt,
               spras,
               land1,
               regio,
               counc,
               bezei
          from {{ ref('DLV_STAGING_T005F') }}
       ),
       join_6 as (
        select join_5.tbrct_bran4_vtext as tbrct_bran4_vtext,
               join_5.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_5.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_5.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_5.zzxgn as zzxgn,
               join_5.comsize as comsize,
               join_5.tdt as tdt,
               join_5.indtyp as indtyp,
               join_5.nodel as nodel,
               join_5.j_1kftind as j_1kftind,
               join_5.j_1kftbus as j_1kftbus,
               join_5.knurl as knurl,
               join_5.cassd as cassd,
               join_5.stcd5 as stcd5,
               join_5.stcd4 as stcd4,
               join_5.stcd3 as stcd3,
               join_5.stcdt as stcdt,
               join_5.fityp as fityp,
               join_5.sperz as sperz,
               join_5.hzuor as hzuor,
               join_5.werks as werks,
               join_5.txjcd as txjcd,
               join_5.katr10 as katr10,
               join_5.katr9 as katr9,
               join_5.katr8 as katr8,
               join_5.katr7 as katr7,
               join_5.katr6 as katr6,
               join_5.katr5 as katr5,
               join_5.katr4 as katr4,
               join_5.katr3 as katr3,
               join_5.katr2 as katr2,
               join_5.katr1 as katr1,
               join_5.bran5 as bran5,
               join_5.bran4 as bran4,
               join_5.bran3 as bran3,
               join_5.bran2 as bran2,
               join_5.bran1 as bran1,
               join_5.stceg as stceg,
               join_5.lzone as lzone,
               join_5.telf2 as telf2,
               join_5.stkzu as stkzu,
               join_5.stkza as stkza,
               join_5.stcd2 as stcd2,
               join_5.stcd1 as stcd1,
               join_5.spras as spras,
               join_5.sperr as sperr,
               join_5.rpmkr as rpmkr,
               join_5.cityc as cityc,
               join_5.counc as counc,
               join_5.pstl2 as pstl2,
               join_5.pfach as pfach,
               join_5.ort02 as ort02,
               join_5.name4 as name4,
               join_5.name3 as name3,
               join_5.loevm as loevm,
               join_5.locco as locco,
               join_5.lifsd as lifsd,
               join_5.lifnr as lifnr,
               join_5.kukla as kukla,
               join_5.ktokd as ktokd,
               join_5.knrza as knrza,
               join_5.faksd as faksd,
               join_5.exabl as exabl,
               join_5.ernam as ernam,
               join_5.erdat as erdat,
               join_5.brsch as brsch,
               join_5.bahns as bahns,
               join_5.bahne as bahne,
               join_5.aufsd as aufsd,
               join_5.anred as anred,
               join_5.adrnr as adrnr,
               join_5.xcpdk as xcpdk,
               join_5.telfx as telfx,
               join_5.telf1 as telf1,
               join_5.stras as stras,
               join_5.sortl as sortl,
               join_5.regio as regio,
               join_5.pstlz as pstlz,
               join_5.ort01 as ort01,
               join_5.name2 as name2,
               join_5.name1 as name1,
               join_5.land1 as land1,
               join_5.kunnr as kunnr,
               join_5.mandt as mandt,
               join_5.t005h_bezei as t005h_bezei,
               p_countytxt.bezei as t005f_bezei
          from join_5
          left outer join p_countytxt
            on join_5.land1 = p_countytxt.land1
           and join_5.regio = p_countytxt.regio
           and join_5.counc = p_countytxt.counc
       ),
       p_classificationtxt as (
        select mandt,
               spras,
               kukla,
               vtext
          from {{ ref('DLV_STAGING_TKUKT') }}
       ),
       join_8 as (
        select join_6.tbrct_bran4_vtext as tbrct_bran4_vtext,
               join_6.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_6.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_6.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_6.zzxgn as zzxgn,
               join_6.comsize as comsize,
               join_6.tdt as tdt,
               join_6.indtyp as indtyp,
               join_6.nodel as nodel,
               join_6.j_1kftind as j_1kftind,
               join_6.j_1kftbus as j_1kftbus,
               join_6.knurl as knurl,
               join_6.cassd as cassd,
               join_6.stcd5 as stcd5,
               join_6.stcd4 as stcd4,
               join_6.stcd3 as stcd3,
               join_6.stcdt as stcdt,
               join_6.fityp as fityp,
               join_6.sperz as sperz,
               join_6.hzuor as hzuor,
               join_6.werks as werks,
               join_6.txjcd as txjcd,
               join_6.katr10 as katr10,
               join_6.katr9 as katr9,
               join_6.katr8 as katr8,
               join_6.katr7 as katr7,
               join_6.katr6 as katr6,
               join_6.katr5 as katr5,
               join_6.katr4 as katr4,
               join_6.katr3 as katr3,
               join_6.katr2 as katr2,
               join_6.katr1 as katr1,
               join_6.bran5 as bran5,
               join_6.bran4 as bran4,
               join_6.bran3 as bran3,
               join_6.bran2 as bran2,
               join_6.bran1 as bran1,
               join_6.stceg as stceg,
               join_6.lzone as lzone,
               join_6.telf2 as telf2,
               join_6.stkzu as stkzu,
               join_6.stkza as stkza,
               join_6.stcd2 as stcd2,
               join_6.stcd1 as stcd1,
               join_6.spras as spras,
               join_6.sperr as sperr,
               join_6.rpmkr as rpmkr,
               join_6.cityc as cityc,
               join_6.counc as counc,
               join_6.pstl2 as pstl2,
               join_6.pfach as pfach,
               join_6.ort02 as ort02,
               join_6.name4 as name4,
               join_6.name3 as name3,
               join_6.loevm as loevm,
               join_6.locco as locco,
               join_6.lifsd as lifsd,
               join_6.lifnr as lifnr,
               join_6.kukla as kukla,
               join_6.ktokd as ktokd,
               join_6.knrza as knrza,
               join_6.faksd as faksd,
               join_6.exabl as exabl,
               join_6.ernam as ernam,
               join_6.erdat as erdat,
               join_6.brsch as brsch,
               join_6.bahns as bahns,
               join_6.bahne as bahne,
               join_6.aufsd as aufsd,
               join_6.anred as anred,
               join_6.adrnr as adrnr,
               join_6.xcpdk as xcpdk,
               join_6.telfx as telfx,
               join_6.telf1 as telf1,
               join_6.stras as stras,
               join_6.sortl as sortl,
               join_6.regio as regio,
               join_6.pstlz as pstlz,
               join_6.ort01 as ort01,
               join_6.name2 as name2,
               join_6.name1 as name1,
               join_6.land1 as land1,
               join_6.kunnr as kunnr,
               join_6.mandt as mandt,
               join_6.t005h_bezei as t005h_bezei,
               join_6.t005f_bezei as t005f_bezei,
               p_classificationtxt.vtext as tkukt_vtext
          from join_6
          left outer join p_classificationtxt
            on join_6.kukla = p_classificationtxt.kukla
       ),
       p_deliveryblock as (
        select mandt,
               spras,
               lifsp,
               vtext
          from {{ ref('DLV_STAGING_TVLST') }}
       ),
       join_7 as (
        select join_8.zzxgn as zzxgn,
               join_8.comsize as comsize,
               join_8.tdt as tdt,
               join_8.indtyp as indtyp,
               join_8.nodel as nodel,
               join_8.j_1kftind as j_1kftind,
               join_8.j_1kftbus as j_1kftbus,
               join_8.knurl as knurl,
               join_8.cassd as cassd,
               join_8.stcd5 as stcd5,
               join_8.stcd4 as stcd4,
               join_8.stcd3 as stcd3,
               join_8.stcdt as stcdt,
               join_8.fityp as fityp,
               join_8.sperz as sperz,
               join_8.hzuor as hzuor,
               join_8.werks as werks,
               join_8.txjcd as txjcd,
               join_8.katr10 as katr10,
               join_8.katr9 as katr9,
               join_8.katr8 as katr8,
               join_8.katr7 as katr7,
               join_8.katr6 as katr6,
               join_8.katr5 as katr5,
               join_8.katr4 as katr4,
               join_8.katr3 as katr3,
               join_8.katr2 as katr2,
               join_8.katr1 as katr1,
               join_8.bran5 as bran5,
               join_8.bran4 as bran4,
               join_8.bran3 as bran3,
               join_8.bran2 as bran2,
               join_8.bran1 as bran1,
               join_8.stceg as stceg,
               join_8.lzone as lzone,
               join_8.telf2 as telf2,
               join_8.stkzu as stkzu,
               join_8.stkza as stkza,
               join_8.stcd2 as stcd2,
               join_8.stcd1 as stcd1,
               join_8.spras as spras,
               join_8.sperr as sperr,
               join_8.rpmkr as rpmkr,
               join_8.cityc as cityc,
               join_8.counc as counc,
               join_8.pstl2 as pstl2,
               join_8.pfach as pfach,
               join_8.ort02 as ort02,
               join_8.name4 as name4,
               join_8.name3 as name3,
               join_8.loevm as loevm,
               join_8.locco as locco,
               join_8.lifsd as lifsd,
               join_8.lifnr as lifnr,
               join_8.kukla as kukla,
               join_8.ktokd as ktokd,
               join_8.knrza as knrza,
               join_8.faksd as faksd,
               join_8.exabl as exabl,
               join_8.ernam as ernam,
               join_8.erdat as erdat,
               join_8.brsch as brsch,
               join_8.bahns as bahns,
               join_8.bahne as bahne,
               join_8.aufsd as aufsd,
               join_8.anred as anred,
               join_8.adrnr as adrnr,
               join_8.xcpdk as xcpdk,
               join_8.telfx as telfx,
               join_8.telf1 as telf1,
               join_8.stras as stras,
               join_8.sortl as sortl,
               join_8.regio as regio,
               join_8.pstlz as pstlz,
               join_8.ort01 as ort01,
               join_8.name2 as name2,
               join_8.name1 as name1,
               join_8.land1 as land1,
               join_8.kunnr as kunnr,
               join_8.mandt as mandt,
               join_8.t005h_bezei as t005h_bezei,
               join_8.t005f_bezei as t005f_bezei,
               join_8.tbrct_bran4_vtext as tbrct_bran4_vtext,
               join_8.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_8.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_8.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_8.tkukt_vtext as tkukt_vtext,
               p_deliveryblock.vtext as tvlst_vtext
          from join_8
          left outer join p_deliveryblock
            on join_8.lifsd = p_deliveryblock.lifsp
       ),
       p_accountgrouptxt as (
        select mandt,
               spras,
               ktokd,
               txt30
          from {{ ref('DLV_STAGING_T077X') }}
       ),
       join_9 as (
        select join_7.t005f_bezei as t005f_bezei,
               join_7.t005h_bezei as t005h_bezei,
               join_7.mandt as mandt,
               join_7.kunnr as kunnr,
               join_7.land1 as land1,
               join_7.name1 as name1,
               join_7.name2 as name2,
               join_7.ort01 as ort01,
               join_7.pstlz as pstlz,
               join_7.regio as regio,
               join_7.sortl as sortl,
               join_7.stras as stras,
               join_7.telf1 as telf1,
               join_7.telfx as telfx,
               join_7.xcpdk as xcpdk,
               join_7.adrnr as adrnr,
               join_7.anred as anred,
               join_7.aufsd as aufsd,
               join_7.bahne as bahne,
               join_7.bahns as bahns,
               join_7.brsch as brsch,
               join_7.erdat as erdat,
               join_7.ernam as ernam,
               join_7.exabl as exabl,
               join_7.faksd as faksd,
               join_7.knrza as knrza,
               join_7.ktokd as ktokd,
               join_7.kukla as kukla,
               join_7.lifnr as lifnr,
               join_7.lifsd as lifsd,
               join_7.locco as locco,
               join_7.loevm as loevm,
               join_7.name3 as name3,
               join_7.name4 as name4,
               join_7.ort02 as ort02,
               join_7.pfach as pfach,
               join_7.pstl2 as pstl2,
               join_7.counc as counc,
               join_7.cityc as cityc,
               join_7.rpmkr as rpmkr,
               join_7.sperr as sperr,
               join_7.spras as spras,
               join_7.stcd1 as stcd1,
               join_7.stcd2 as stcd2,
               join_7.stkza as stkza,
               join_7.telf2 as telf2,
               join_7.stkzu as stkzu,
               join_7.lzone as lzone,
               join_7.stceg as stceg,
               join_7.bran1 as bran1,
               join_7.bran2 as bran2,
               join_7.bran3 as bran3,
               join_7.bran4 as bran4,
               join_7.bran5 as bran5,
               join_7.katr1 as katr1,
               join_7.katr2 as katr2,
               join_7.katr3 as katr3,
               join_7.katr4 as katr4,
               join_7.katr5 as katr5,
               join_7.katr6 as katr6,
               join_7.katr7 as katr7,
               join_7.katr8 as katr8,
               join_7.katr9 as katr9,
               join_7.katr10 as katr10,
               join_7.txjcd as txjcd,
               join_7.werks as werks,
               join_7.hzuor as hzuor,
               join_7.sperz as sperz,
               join_7.fityp as fityp,
               join_7.stcdt as stcdt,
               join_7.stcd3 as stcd3,
               join_7.stcd4 as stcd4,
               join_7.stcd5 as stcd5,
               join_7.cassd as cassd,
               join_7.knurl as knurl,
               join_7.j_1kftbus as j_1kftbus,
               join_7.j_1kftind as j_1kftind,
               join_7.nodel as nodel,
               join_7.indtyp as indtyp,
               join_7.tdt as tdt,
               join_7.comsize as comsize,
               join_7.zzxgn as zzxgn,
               join_7.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_7.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_7.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_7.tbrct_bran4_vtext as tbrct_bran4_vtext,
               join_7.tvlst_vtext as tvlst_vtext,
               join_7.tkukt_vtext as tkukt_vtext,
               p_accountgrouptxt.txt30 as t077x_txt30
          from join_7
          left outer join p_accountgrouptxt
            on join_7.ktokd = p_accountgrouptxt.ktokd
       ),
       p_centralbillingblocktxt as (
        select mandt,
               spras,
               faksp,
               vtext
          from {{ ref('DLV_STAGING_TVFST') }}
       ),
       join_10 as (
        select join_9.tkukt_vtext as tkukt_vtext,
               join_9.tvlst_vtext as tvlst_vtext,
               join_9.tbrct_bran4_vtext as tbrct_bran4_vtext,
               join_9.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_9.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_9.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_9.zzxgn as zzxgn,
               join_9.comsize as comsize,
               join_9.tdt as tdt,
               join_9.indtyp as indtyp,
               join_9.nodel as nodel,
               join_9.j_1kftind as j_1kftind,
               join_9.j_1kftbus as j_1kftbus,
               join_9.knurl as knurl,
               join_9.cassd as cassd,
               join_9.stcd5 as stcd5,
               join_9.stcd4 as stcd4,
               join_9.stcd3 as stcd3,
               join_9.stcdt as stcdt,
               join_9.fityp as fityp,
               join_9.sperz as sperz,
               join_9.hzuor as hzuor,
               join_9.werks as werks,
               join_9.txjcd as txjcd,
               join_9.katr10 as katr10,
               join_9.katr9 as katr9,
               join_9.katr8 as katr8,
               join_9.katr7 as katr7,
               join_9.katr6 as katr6,
               join_9.katr5 as katr5,
               join_9.katr4 as katr4,
               join_9.katr3 as katr3,
               join_9.katr2 as katr2,
               join_9.katr1 as katr1,
               join_9.bran5 as bran5,
               join_9.bran4 as bran4,
               join_9.bran3 as bran3,
               join_9.bran2 as bran2,
               join_9.bran1 as bran1,
               join_9.stceg as stceg,
               join_9.lzone as lzone,
               join_9.telf2 as telf2,
               join_9.stkzu as stkzu,
               join_9.stkza as stkza,
               join_9.stcd2 as stcd2,
               join_9.stcd1 as stcd1,
               join_9.spras as spras,
               join_9.sperr as sperr,
               join_9.rpmkr as rpmkr,
               join_9.cityc as cityc,
               join_9.counc as counc,
               join_9.pstl2 as pstl2,
               join_9.pfach as pfach,
               join_9.ort02 as ort02,
               join_9.name4 as name4,
               join_9.name3 as name3,
               join_9.loevm as loevm,
               join_9.locco as locco,
               join_9.lifsd as lifsd,
               join_9.lifnr as lifnr,
               join_9.kukla as kukla,
               join_9.ktokd as ktokd,
               join_9.knrza as knrza,
               join_9.faksd as faksd,
               join_9.exabl as exabl,
               join_9.ernam as ernam,
               join_9.erdat as erdat,
               join_9.brsch as brsch,
               join_9.bahns as bahns,
               join_9.bahne as bahne,
               join_9.aufsd as aufsd,
               join_9.anred as anred,
               join_9.adrnr as adrnr,
               join_9.xcpdk as xcpdk,
               join_9.telfx as telfx,
               join_9.telf1 as telf1,
               join_9.stras as stras,
               join_9.sortl as sortl,
               join_9.regio as regio,
               join_9.pstlz as pstlz,
               join_9.ort01 as ort01,
               join_9.name2 as name2,
               join_9.name1 as name1,
               join_9.land1 as land1,
               join_9.kunnr as kunnr,
               join_9.mandt as mandt,
               join_9.t005h_bezei as t005h_bezei,
               join_9.t005f_bezei as t005f_bezei,
               join_9.t077x_txt30 as t077x_txt30,
               p_centralbillingblocktxt.vtext as tvfst_vtext
          from join_9
          left outer join p_centralbillingblocktxt
            on join_9.faksd = p_centralbillingblocktxt.faksp
       ),
       p_regiontxt as (
        select mandt,
               spras,
               land1,
               bland,
               bezei
          from {{ ref('DLV_STAGING_T005U') }}
       ),
       join_11 as (
        select join_10.tkukt_vtext as tkukt_vtext,
               join_10.tvlst_vtext as tvlst_vtext,
               join_10.tbrct_bran4_vtext as tbrct_bran4_vtext,
               join_10.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_10.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_10.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_10.zzxgn as zzxgn,
               join_10.comsize as comsize,
               join_10.tdt as tdt,
               join_10.indtyp as indtyp,
               join_10.nodel as nodel,
               join_10.j_1kftind as j_1kftind,
               join_10.j_1kftbus as j_1kftbus,
               join_10.knurl as knurl,
               join_10.cassd as cassd,
               join_10.stcd5 as stcd5,
               join_10.stcd4 as stcd4,
               join_10.stcd3 as stcd3,
               join_10.stcdt as stcdt,
               join_10.fityp as fityp,
               join_10.sperz as sperz,
               join_10.hzuor as hzuor,
               join_10.werks as werks,
               join_10.txjcd as txjcd,
               join_10.katr10 as katr10,
               join_10.katr9 as katr9,
               join_10.katr8 as katr8,
               join_10.katr7 as katr7,
               join_10.katr6 as katr6,
               join_10.katr5 as katr5,
               join_10.katr4 as katr4,
               join_10.katr3 as katr3,
               join_10.katr2 as katr2,
               join_10.katr1 as katr1,
               join_10.bran5 as bran5,
               join_10.bran4 as bran4,
               join_10.bran3 as bran3,
               join_10.bran2 as bran2,
               join_10.bran1 as bran1,
               join_10.stceg as stceg,
               join_10.lzone as lzone,
               join_10.telf2 as telf2,
               join_10.stkzu as stkzu,
               join_10.stkza as stkza,
               join_10.stcd2 as stcd2,
               join_10.stcd1 as stcd1,
               join_10.spras as spras,
               join_10.sperr as sperr,
               join_10.rpmkr as rpmkr,
               join_10.cityc as cityc,
               join_10.counc as counc,
               join_10.pstl2 as pstl2,
               join_10.pfach as pfach,
               join_10.ort02 as ort02,
               join_10.name4 as name4,
               join_10.name3 as name3,
               join_10.loevm as loevm,
               join_10.locco as locco,
               join_10.lifsd as lifsd,
               join_10.lifnr as lifnr,
               join_10.kukla as kukla,
               join_10.ktokd as ktokd,
               join_10.knrza as knrza,
               join_10.faksd as faksd,
               join_10.exabl as exabl,
               join_10.ernam as ernam,
               join_10.erdat as erdat,
               join_10.brsch as brsch,
               join_10.bahns as bahns,
               join_10.bahne as bahne,
               join_10.aufsd as aufsd,
               join_10.anred as anred,
               join_10.adrnr as adrnr,
               join_10.xcpdk as xcpdk,
               join_10.telfx as telfx,
               join_10.telf1 as telf1,
               join_10.stras as stras,
               join_10.sortl as sortl,
               join_10.regio as regio,
               join_10.pstlz as pstlz,
               join_10.ort01 as ort01,
               join_10.name2 as name2,
               join_10.name1 as name1,
               join_10.land1 as land1,
               join_10.kunnr as kunnr,
               join_10.mandt as mandt,
               join_10.t005h_bezei as t005h_bezei,
               join_10.t005f_bezei as t005f_bezei,
               join_10.t077x_txt30 as t077x_txt30,
               join_10.tvfst_vtext as tvfst_vtext,
               p_regiontxt.bezei as t005u_bezei
          from join_10
          left outer join p_regiontxt
            on join_10.land1 = p_regiontxt.land1
           and join_10.regio = p_regiontxt.bland
       ),
       p_countrytxt as (
        select mandt,
               spras,
               land1,
               landx,
               natio,
               landx50,
               natio50,
               prq_spregt
          from {{ ref('DLV_STAGING_T005T') }}
       ),
       join_12 as (
        select join_11.tvfst_vtext as tvfst_vtext,
               join_11.t077x_txt30 as t077x_txt30,
               join_11.t005f_bezei as t005f_bezei,
               join_11.t005h_bezei as t005h_bezei,
               join_11.mandt as mandt,
               join_11.kunnr as kunnr,
               join_11.land1 as land1,
               join_11.name1 as name1,
               join_11.name2 as name2,
               join_11.ort01 as ort01,
               join_11.pstlz as pstlz,
               join_11.regio as regio,
               join_11.sortl as sortl,
               join_11.stras as stras,
               join_11.telf1 as telf1,
               join_11.telfx as telfx,
               join_11.xcpdk as xcpdk,
               join_11.adrnr as adrnr,
               join_11.anred as anred,
               join_11.aufsd as aufsd,
               join_11.bahne as bahne,
               join_11.bahns as bahns,
               join_11.brsch as brsch,
               join_11.erdat as erdat,
               join_11.ernam as ernam,
               join_11.exabl as exabl,
               join_11.faksd as faksd,
               join_11.knrza as knrza,
               join_11.ktokd as ktokd,
               join_11.kukla as kukla,
               join_11.lifnr as lifnr,
               join_11.lifsd as lifsd,
               join_11.locco as locco,
               join_11.loevm as loevm,
               join_11.name3 as name3,
               join_11.name4 as name4,
               join_11.ort02 as ort02,
               join_11.pfach as pfach,
               join_11.pstl2 as pstl2,
               join_11.counc as counc,
               join_11.cityc as cityc,
               join_11.rpmkr as rpmkr,
               join_11.sperr as sperr,
               join_11.spras as spras,
               join_11.stcd1 as stcd1,
               join_11.stcd2 as stcd2,
               join_11.stkza as stkza,
               join_11.stkzu as stkzu,
               join_11.telf2 as telf2,
               join_11.lzone as lzone,
               join_11.stceg as stceg,
               join_11.bran1 as bran1,
               join_11.bran2 as bran2,
               join_11.bran3 as bran3,
               join_11.bran4 as bran4,
               join_11.bran5 as bran5,
               join_11.katr1 as katr1,
               join_11.katr2 as katr2,
               join_11.katr3 as katr3,
               join_11.katr4 as katr4,
               join_11.katr5 as katr5,
               join_11.katr6 as katr6,
               join_11.katr7 as katr7,
               join_11.katr8 as katr8,
               join_11.katr9 as katr9,
               join_11.katr10 as katr10,
               join_11.txjcd as txjcd,
               join_11.werks as werks,
               join_11.hzuor as hzuor,
               join_11.sperz as sperz,
               join_11.fityp as fityp,
               join_11.stcdt as stcdt,
               join_11.stcd3 as stcd3,
               join_11.stcd4 as stcd4,
               join_11.stcd5 as stcd5,
               join_11.cassd as cassd,
               join_11.knurl as knurl,
               join_11.j_1kftbus as j_1kftbus,
               join_11.j_1kftind as j_1kftind,
               join_11.nodel as nodel,
               join_11.indtyp as indtyp,
               join_11.tdt as tdt,
               join_11.comsize as comsize,
               join_11.zzxgn as zzxgn,
               join_11.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_11.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_11.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_11.tbrct_bran4_vtext as tbrct_bran4_vtext,
               join_11.tvlst_vtext as tvlst_vtext,
               join_11.tkukt_vtext as tkukt_vtext,
               join_11.t005u_bezei as t005u_bezei,
               p_countrytxt.landx as t005t_landx
          from join_11
          left outer join p_countrytxt
            on join_11.land1 = p_countrytxt.land1
       ),
       j_kna1 as (
        select join_12.tvfst_vtext as tvfst_vtext,
               join_12.t077x_txt30 as t077x_txt30,
               join_12.t005f_bezei as t005f_bezei,
               join_12.t005h_bezei as t005h_bezei,
               join_12.mandt as mandt,
               join_12.kunnr as kunnr,
               join_12.land1 as land1,
               join_12.name1 as name1,
               join_12.name2 as name2,
               join_12.ort01 as ort01,
               join_12.pstlz as pstlz,
               join_12.regio as regio,
               join_12.sortl as sortl,
               join_12.stras as stras,
               join_12.telf1 as telf1,
               join_12.telfx as telfx,
               join_12.xcpdk as xcpdk,
               join_12.adrnr as adrnr,
               join_12.anred as anred,
               join_12.aufsd as aufsd,
               join_12.bahne as bahne,
               join_12.bahns as bahns,
               join_12.brsch as brsch,
               join_12.erdat as erdat,
               join_12.ernam as ernam,
               join_12.exabl as exabl,
               join_12.faksd as faksd,
               join_12.knrza as knrza,
               join_12.ktokd as ktokd,
               join_12.kukla as kukla,
               join_12.lifnr as lifnr,
               join_12.lifsd as lifsd,
               join_12.locco as locco,
               join_12.loevm as loevm,
               join_12.name3 as name3,
               join_12.name4 as name4,
               join_12.ort02 as ort02,
               join_12.pfach as pfach,
               join_12.pstl2 as pstl2,
               join_12.counc as counc,
               join_12.cityc as cityc,
               join_12.rpmkr as rpmkr,
               join_12.sperr as sperr,
               join_12.spras as spras,
               join_12.stcd1 as stcd1,
               join_12.stcd2 as stcd2,
               join_12.stkza as stkza,
               join_12.stkzu as stkzu,
               join_12.telf2 as telf2,
               join_12.lzone as lzone,
               join_12.stceg as stceg,
               join_12.bran1 as bran1,
               join_12.bran2 as bran2,
               join_12.bran3 as bran3,
               join_12.bran4 as bran4,
               join_12.bran5 as bran5,
               join_12.katr1 as katr1,
               join_12.katr2 as katr2,
               join_12.katr3 as katr3,
               join_12.katr4 as katr4,
               join_12.katr5 as katr5,
               join_12.katr6 as katr6,
               join_12.katr7 as katr7,
               join_12.katr8 as katr8,
               join_12.katr9 as katr9,
               join_12.katr10 as katr10,
               join_12.txjcd as txjcd,
               join_12.werks as werks,
               join_12.hzuor as hzuor,
               join_12.sperz as sperz,
               join_12.fityp as fityp,
               join_12.stcdt as stcdt,
               join_12.stcd3 as stcd3,
               join_12.stcd4 as stcd4,
               join_12.stcd5 as stcd5,
               join_12.cassd as cassd,
               join_12.knurl as knurl,
               join_12.j_1kftbus as j_1kftbus,
               join_12.j_1kftind as j_1kftind,
               join_12.nodel as nodel,
               join_12.indtyp as indtyp,
               join_12.tdt as tdt,
               join_12.comsize as comsize,
               join_12.zzxgn as zzxgn,
               join_12.tbrct_bran1_vtext as tbrct_bran1_vtext,
               join_12.tbrct_bran2_vtext as tbrct_bran2_vtext,
               join_12.tbrct_bran3_vtext as tbrct_bran3_vtext,
               join_12.tbrct_bran4_vtext as tbrct_bran4_vtext,
               join_12.tvlst_vtext as tvlst_vtext,
               join_12.tkukt_vtext as tkukt_vtext,
               join_12.t005u_bezei as t005u_bezei,
               join_12.t005t_landx as t005t_landx,
               p_industrycode5text.vtext as tbrct_bran5_vtext
          from join_12
          left outer join p_industrycode5text
            on join_12.bran5 = p_industrycode5text.braco
       ) select mandt as client,
       kunnr as customernumber,
       iff((name1 is null) or name1 = '','',trim(name1)) || iff((name2 is null) or name2 = '','', ' ' || trim(name2)) || iff((name3 is null) or name3 = '','',' ' || trim(name3)) || iff((name4 is null) or name4 = '','',' ' || trim(name4)) as customername,
       land1 as countrykey,
       t005t_landx as countryname,
       name1 as name1,
       name2 as name2,
       ort01 as city,
       pstlz as postalcode,
       regio as region,
       t005u_bezei as regionname,
       sortl as sortfield,
       stras as housenumberandstreet,
       telf1 as firsttelephonenumber,
       telfx as faxnumber,
       xcpdk as indicator_istheaccountaone_timeaccount,
       adrnr as address,
       anred as title,
       aufsd as centralorderblockforcustomer,
       bahne as expresstrainstation,
       bahns as trainstation,
       brsch as industrykey,
       erdat as dateonwhichtherecordwascreated,
       ernam as nameofpersonwhocreatedtheobject,
       exabl as indicatorunloadingpointsexist,
       faksd as centralbillingblockforcustomer,
       tvfst_vtext as centralbillingblockforcustomerdesc,
       knrza as accountnumberofanalternativepayer,
       ktokd as customeraccountgroup,
       t077x_txt30 as customeraccountgroupdesc,
       kukla as customerclassification,
       tkukt_vtext as customerclassificationdesc,
       lifnr as accountnumberofvendororcreditor,
       lifsd as centraldeliveryblockforthecustomer,
       tvlst_vtext as centraldeliveryblockforthecustomerdesc,
       locco as citycoordinates,
       loevm as centraldeletionflagformasterrecord,
       name3 as name3,
       name4 as name4,
       ort02 as district,
       pfach as pobox,
       pstl2 as poboxpostalcode,
       counc as countrycode,
       t005f_bezei as countycodedesc,
       cityc as citycode,
       t005h_bezei as citycodedesc,
       rpmkr as regionalmarket,
       sperr as centralpostingblock,
       spras as languagekey,
       stcd1 as taxnumber1,
       stcd2 as taxnumber2,
       stkza as indicatorbusinesspartnersubjecttoequalizationtax,
       stkzu as liableforvat,
       telf2 as secondtelephonenumber,
       lzone as transportationzonetoorfromwhichthegoodsaredelivered,
       stceg as vatregistrationnumber,
       bran1 as industrycode1,
       tbrct_bran1_vtext as industrycode1desc,
       bran2 as industrycode2,
       tbrct_bran2_vtext as industrycode2desc,
       bran3 as industrycode3,
       tbrct_bran3_vtext as industrycode3desc,
       bran4 as industrycode4,
       tbrct_bran4_vtext as industrycode4desc,
       bran5 as industrycode5,
       tbrct_bran5_vtext as industrycode5desc,
       katr1 as attribute1,
       katr2 as attribute2,
       katr3 as attribute3,
       katr4 as attribute4,
       katr5 as attribute5,
       katr6 as attribute6,
       katr7 as attribute7,
       katr8 as attribute8,
       katr9 as attribute9,
       katr10 as attribute10,
       txjcd as taxjurisdiction,
       werks as plant,
       hzuor as assignmenttohierarchy,
       sperz as paymentblock,
       fityp as taxtype,
       stcdt as taxnumbertype,
       stcd3 as taxnumber3,
       stcd4 as taxnumber4,
       stcd5 as taxnumber5,
       cassd as centralsalesblockforcustomer,
       knurl as uniformresourcelocator,
       j_1kftbus as typeofbusiness,
       j_1kftind as typeofindustry,
       nodel as centraldeletionblockformasterrecord,
       indtyp as industrymaintype,
       tdt as taxdeclarationtype,
       comsize as companysize,
       zzxgn as groupidentifier
  from j_kna1