with blv_mdm_sapcustomer_qv_source as (
        select housenumberandstreet,
               countrykey,
               pobox,
               address,
               name2,
               name3,
               typeofbusiness,
               taxnumber2,
               vatregistrationnumber,
               region,
               customeraccountgroup,
               taxnumber1,
               regionname,
               customernumber,
               centraldeletionflagformasterrecord,
               customeraccountgroupdesc,
               city,
               client,
               customername,
               poboxpostalcode,
               accountnumberofvendororcreditor,
               postalcode,
               sortfield,
               countrycode,
               firsttelephonenumber,
               faxnumber,
               name1,
               citycoordinates,
               taxjurisdiction,
               district,
               nameofpersonwhocreatedtheobject,
               countycodedesc,
               countryname,
               name4,
               groupidentifier,
               dateonwhichtherecordwascreated,
               title,
               uniformresourcelocator
          from {{ ref('BLV_MDM_SAPCUSTOMER_QV') }}
       ),
       p_cust as (
        select client,
               customernumber,
               customername,
               title,
               name1,
               name2,
               name3,
               name4,
               sortfield,
               housenumberandstreet,
               city,
               district,
               postalcode,
               pobox,
               poboxpostalcode,
               countrycode as countycode,
               countycodedesc,
               region,
               regionname,
               countrykey,
               countryname,
               firsttelephonenumber,
               faxnumber,
               address,
               dateonwhichtherecordwascreated,
               nameofpersonwhocreatedtheobject,
               customeraccountgroup,
               customeraccountgroupdesc,
               accountnumberofvendororcreditor,
               citycoordinates,
               centraldeletionflagformasterrecord,
               taxnumber1,
               taxnumber2,
               vatregistrationnumber,
               taxjurisdiction,
               uniformresourcelocator,
               typeofbusiness,
               groupidentifier
          from {{ ref('BLV_MDM_SAPCUSTOMER_QV') }}
       ),
       aggregation_2 as (
        select client,
               losercustomernumber,
               max(winnercustomernumber) as winnercustomernumber,
               max(winnercustomercount) as winnercustomercount
          from {{ ref('BLV_MDM_SAPCUSTOMERMERGESEQUENCE_QV') }}
         group by client,
                  losercustomernumber
       ),
       j_custwithcustmerge as (
        select p_cust.client as client,
               p_cust.customernumber as customernumber,
               p_cust.customername as customername,
               p_cust.title as title,
               p_cust.name1 as name1,
               p_cust.name2 as name2,
               p_cust.name3 as name3,
               p_cust.name4 as name4,
               p_cust.sortfield as sortfield,
               p_cust.housenumberandstreet as housenumberandstreet,
               p_cust.city as city,
               p_cust.district as district,
               p_cust.postalcode as postalcode,
               p_cust.pobox as pobox,
               p_cust.poboxpostalcode as poboxpostalcode,
               p_cust.countycode as countycode,
               p_cust.countycodedesc as countycodedesc,
               p_cust.region as region,
               p_cust.regionname as regionname,
               p_cust.countrykey as countrykey,
               p_cust.countryname as countryname,
               p_cust.firsttelephonenumber as firsttelephonenumber,
               p_cust.faxnumber as faxnumber,
               p_cust.address as address,
               p_cust.dateonwhichtherecordwascreated as dateonwhichtherecordwascreated,
               p_cust.nameofpersonwhocreatedtheobject as nameofpersonwhocreatedtheobject,
               p_cust.customeraccountgroup as customeraccountgroup,
               p_cust.customeraccountgroupdesc as customeraccountgroupdesc,
               p_cust.accountnumberofvendororcreditor as accountnumberofvendororcreditor,
               p_cust.citycoordinates as citycoordinates,
               p_cust.centraldeletionflagformasterrecord as centraldeletionflagformasterrecord,
               p_cust.taxnumber1 as taxnumber1,
               p_cust.taxnumber2 as taxnumber2,
               p_cust.vatregistrationnumber as vatregistrationnumber,
               p_cust.taxjurisdiction as taxjurisdiction,
               p_cust.uniformresourcelocator as uniformresourcelocator,
               p_cust.typeofbusiness as typeofbusiness,
               p_cust.groupidentifier as groupidentifier,
               aggregation_2.winnercustomernumber as cms_winnercustomernumber,
               aggregation_2.winnercustomercount as cms_winnercustomercount
          from p_cust
          left outer join aggregation_2
            on p_cust.client = aggregation_2.client
           and p_cust.customernumber = aggregation_2.losercustomernumber
       ),
       p_accountmaster as (
        select accountid,
               accountname,
               deleted,
               masterrecordid,
               accounttype,
               recordtypeid,
               recordname,
               recorddescription,
               parentid,
               parentname,
               street,
               city,
               stateprovince,
               zippostalcode,
               country,
               state,
               countrycode,
               addresslatitude,
               addresslongitude,
               billinggeocodeaccuracy,
               shippingstreet,
               shippingcity,
               shippingstateprovince,
               shippingzippostalcode,
               shippingcountry,
               shippingstateprovincecode,
               shippingcountrycode,
               shippinglatitude,
               shippinglongitude,
               shippinggeocodeaccuracy,
               accountphone,
               website,
               photourl,
               siccode,
               industry,
               employees,
               ownership,
               tickersymbol,
               accountdescription,
               accountrating,
               currency,
               ownerid,
               ownername,
               createddate,
               createdbyid,
               createdbyname,
               lastmodifieddate,
               lastmodifiedbyid,
               modifiedbyname,
               systemmodstamp,
               lastactivity,
               lastvieweddate,
               lastreferenceddate,
               partneraccount,
               datacomkey,
               jigsawcompanyid,
               accountsource,
               sicdescription,
               accesshours,
               businesshoursdonotuse,
               latitude,
               longitude,
               billingcontactfiltercriteria,
               billingcontactformat,
               billingdayofmonth,
               calendarcyclestart,
               creditmemoemailtemplate,
               defaultcreditmemotemplate,
               defaultinvoicestatementtemplate,
               defaultinvoicetemplate,
               invoiceemailtemplate,
               taxexemptstatus,
               taxexempt,
               excludefromterritoryassignmentrules,
               externalid,
               highvalueaccount,
               slaexpirationdate,
               sla,
               taxcode,
               tax,
               upsellopportunity,
               creditblock,
               preferredlanguage,
               channelpartnertype,
               deliveryblock,
               partnertype,
               markfordeletion,
               tier,
               openopportunityamount,
               orderblock,
               salesblock,
               suspensionrejectionreason,
               careoflocal,
               careof,
               fieldcomments,
               erpcustomerid,
               globalgroupnumber,
               nationalgroupnumber,
               salesgroupnumber,
               addressstatus,
               resubmissionreason,
               partneraccountmanager,
               territoryregion,
               businessunit,
               customertype,
               district,
               citylocal,
               subregion,
               territorycode,
               territoryname,
               clinicaltype,
               disablemyilmncustomerdashboardaccess,
               myilmnaccesschangelog,
               reasonforchangingmyilmnaccess,
               countrylocal,
               stateprovincelocal,
               street2local,
               streetlocal,
               zippostalcodelocal,
               accountgroup,
               billingissue,
               accountstatus,
               accountleadsourcetextfield,
               active,
               contactid,
               customerpriority,
               locationid,
               numberoflocations,
               accountfax,
               accountnumber,
               accountsite,
               accountnamelocal,
               annualrevenue,
               preferredtechnician,
               fieldsupportcountforautodispatch,
               productfamily,
               regulatorytype,
               legacysfdcrecordid,
               customersubtype,
               isupdatedbysystem,
               marketsegment,
               populationgenomics,
               externalrecordid,
               primarymarketsegment,
               channelprogramname,
               channelprogramlevelname,
               primarymarketsegmentpercentallocation,
               entityacquisitionid
          from {{ ref('BLV_MDM_SFDCACCOUNTMASTER_QV') }}
       ),
       rank_1 as (
        select accountid,
               accountname,
               deleted,
               masterrecordid,
               accounttype,
               recordtypeid,
               recordname,
               recorddescription,
               parentid,
               parentname,
               street,
               city,
               stateprovince,
               zippostalcode,
               country,
               state,
               countrycode,
               addresslatitude,
               addresslongitude,
               billinggeocodeaccuracy,
               shippingstreet,
               shippingcity,
               shippingstateprovince,
               shippingzippostalcode,
               shippingcountry,
               shippingstateprovincecode,
               shippingcountrycode,
               shippinglatitude,
               shippinglongitude,
               shippinggeocodeaccuracy,
               accountphone,
               website,
               photourl,
               siccode,
               industry,
               employees,
               ownership,
               tickersymbol,
               accountdescription,
               accountrating,
               currency,
               ownerid,
               ownername,
               createddate,
               createdbyid,
               createdbyname,
               lastmodifieddate,
               lastmodifiedbyid,
               modifiedbyname,
               systemmodstamp,
               lastactivity,
               lastvieweddate,
               lastreferenceddate,
               partneraccount,
               datacomkey,
               jigsawcompanyid,
               accountsource,
               sicdescription,
               accesshours,
               businesshoursdonotuse,
               latitude,
               longitude,
               billingcontactfiltercriteria,
               billingcontactformat,
               billingdayofmonth,
               calendarcyclestart,
               creditmemoemailtemplate,
               defaultcreditmemotemplate,
               defaultinvoicestatementtemplate,
               defaultinvoicetemplate,
               invoiceemailtemplate,
               taxexemptstatus,
               taxexempt,
               excludefromterritoryassignmentrules,
               externalid,
               highvalueaccount,
               slaexpirationdate,
               sla,
               taxcode,
               tax,
               upsellopportunity,
               creditblock,
               preferredlanguage,
               channelpartnertype,
               deliveryblock,
               partnertype,
               markfordeletion,
               tier,
               openopportunityamount,
               orderblock,
               salesblock,
               suspensionrejectionreason,
               careoflocal,
               careof,
               fieldcomments,
               erpcustomerid,
               globalgroupnumber,
               nationalgroupnumber,
               salesgroupnumber,
               addressstatus,
               resubmissionreason,
               partneraccountmanager,
               territoryregion,
               businessunit,
               customertype,
               district,
               citylocal,
               subregion,
               territorycode,
               territoryname,
               clinicaltype,
               disablemyilmncustomerdashboardaccess,
               myilmnaccesschangelog,
               reasonforchangingmyilmnaccess,
               countrylocal,
               stateprovincelocal,
               street2local,
               streetlocal,
               zippostalcodelocal,
               accountgroup,
               billingissue,
               accountstatus,
               accountleadsourcetextfield,
               active,
               contactid,
               customerpriority,
               locationid,
               numberoflocations,
               accountfax,
               accountnumber,
               accountsite,
               accountnamelocal,
               annualrevenue,
               preferredtechnician,
               fieldsupportcountforautodispatch,
               productfamily,
               regulatorytype,
               legacysfdcrecordid,
               customersubtype,
               isupdatedbysystem,
               marketsegment,
               populationgenomics,
               externalrecordid,
               primarymarketsegment,
               primarymarketsegmentpercentallocation,
               channelprogramname,
               channelprogramlevelname,
               entityacquisitionid,
               row_number() over (partition by erpcustomerid order by accountid desc) as accountcustomer_rank
          from p_accountmaster qualify accountcustomer_rank <= 1
       ),
       aggregation_1 as (
        select erpcustomerid,
               count(erpcustomerid) as agg_erpcustomerid
          from p_accountmaster
         group by erpcustomerid
       ),
       join_1 as (
        select rank_1.accountid as accountid,
               rank_1.accountname as accountname,
               rank_1.deleted as deleted,
               rank_1.masterrecordid as masterrecordid,
               rank_1.accounttype as accounttype,
               rank_1.recordtypeid as recordtypeid,
               rank_1.recordname as recordname,
               rank_1.recorddescription as recorddescription,
               rank_1.parentid as parentid,
               rank_1.parentname as parentname,
               rank_1.street as street,
               rank_1.city as city,
               rank_1.stateprovince as stateprovince,
               rank_1.zippostalcode as zippostalcode,
               rank_1.country as country,
               rank_1.state as state,
               rank_1.countrycode as countrycode,
               rank_1.addresslatitude as addresslatitude,
               rank_1.addresslongitude as addresslongitude,
               rank_1.billinggeocodeaccuracy as billinggeocodeaccuracy,
               rank_1.shippingstreet as shippingstreet,
               rank_1.shippingcity as shippingcity,
               rank_1.shippingstateprovince as shippingstateprovince,
               rank_1.shippingzippostalcode as shippingzippostalcode,
               rank_1.shippingcountry as shippingcountry,
               rank_1.shippingstateprovincecode as shippingstateprovincecode,
               rank_1.shippingcountrycode as shippingcountrycode,
               rank_1.shippinglatitude as shippinglatitude,
               rank_1.shippinglongitude as shippinglongitude,
               rank_1.shippinggeocodeaccuracy as shippinggeocodeaccuracy,
               rank_1.accountphone as accountphone,
               rank_1.website as website,
               rank_1.photourl as photourl,
               rank_1.siccode as siccode,
               rank_1.industry as industry,
               rank_1.employees as employees,
               rank_1.ownership as ownership,
               rank_1.tickersymbol as tickersymbol,
               rank_1.accountdescription as accountdescription,
               rank_1.accountrating as accountrating,
               rank_1.currency as currency,
               rank_1.ownerid as ownerid,
               rank_1.ownername as ownername,
               rank_1.createddate as createddate,
               rank_1.createdbyid as createdbyid,
               rank_1.createdbyname as createdbyname,
               rank_1.lastmodifieddate as lastmodifieddate,
               rank_1.lastmodifiedbyid as lastmodifiedbyid,
               rank_1.modifiedbyname as modifiedbyname,
               rank_1.systemmodstamp as systemmodstamp,
               rank_1.lastactivity as lastactivity,
               rank_1.lastvieweddate as lastvieweddate,
               rank_1.lastreferenceddate as lastreferenceddate,
               rank_1.partneraccount as partneraccount,
               rank_1.datacomkey as datacomkey,
               rank_1.jigsawcompanyid as jigsawcompanyid,
               rank_1.accountsource as accountsource,
               rank_1.sicdescription as sicdescription,
               rank_1.accesshours as accesshours,
               rank_1.businesshoursdonotuse as businesshoursdonotuse,
               rank_1.latitude as latitude,
               rank_1.longitude as longitude,
               rank_1.billingcontactfiltercriteria as billingcontactfiltercriteria,
               rank_1.billingcontactformat as billingcontactformat,
               rank_1.billingdayofmonth as billingdayofmonth,
               rank_1.calendarcyclestart as calendarcyclestart,
               rank_1.creditmemoemailtemplate as creditmemoemailtemplate,
               rank_1.defaultcreditmemotemplate as defaultcreditmemotemplate,
               rank_1.defaultinvoicestatementtemplate as defaultinvoicestatementtemplate,
               rank_1.defaultinvoicetemplate as defaultinvoicetemplate,
               rank_1.invoiceemailtemplate as invoiceemailtemplate,
               rank_1.taxexemptstatus as taxexemptstatus,
               rank_1.taxexempt as taxexempt,
               rank_1.excludefromterritoryassignmentrules as excludefromterritoryassignmentrules,
               rank_1.externalid as externalid,
               rank_1.highvalueaccount as highvalueaccount,
               rank_1.slaexpirationdate as slaexpirationdate,
               rank_1.sla as sla,
               rank_1.taxcode as taxcode,
               rank_1.tax as tax,
               rank_1.upsellopportunity as upsellopportunity,
               rank_1.creditblock as creditblock,
               rank_1.preferredlanguage as preferredlanguage,
               rank_1.channelpartnertype as channelpartnertype,
               rank_1.deliveryblock as deliveryblock,
               rank_1.partnertype as partnertype,
               rank_1.markfordeletion as markfordeletion,
               rank_1.tier as tier,
               rank_1.openopportunityamount as openopportunityamount,
               rank_1.orderblock as orderblock,
               rank_1.salesblock as salesblock,
               rank_1.suspensionrejectionreason as suspensionrejectionreason,
               rank_1.careoflocal as careoflocal,
               rank_1.careof as careof,
               rank_1.fieldcomments as fieldcomments,
               rank_1.erpcustomerid as erpcustomerid,
               rank_1.globalgroupnumber as globalgroupnumber,
               rank_1.nationalgroupnumber as nationalgroupnumber,
               rank_1.salesgroupnumber as salesgroupnumber,
               rank_1.addressstatus as addressstatus,
               rank_1.resubmissionreason as resubmissionreason,
               rank_1.partneraccountmanager as partneraccountmanager,
               rank_1.territoryregion as territoryregion,
               rank_1.businessunit as businessunit,
               rank_1.customertype as customertype,
               rank_1.district as district,
               rank_1.citylocal as citylocal,
               rank_1.subregion as subregion,
               rank_1.territorycode as territorycode,
               rank_1.territoryname as territoryname,
               rank_1.clinicaltype as clinicaltype,
               rank_1.disablemyilmncustomerdashboardaccess as disablemyilmncustomerdashboardaccess,
               rank_1.myilmnaccesschangelog as myilmnaccesschangelog,
               rank_1.reasonforchangingmyilmnaccess as reasonforchangingmyilmnaccess,
               rank_1.countrylocal as countrylocal,
               rank_1.stateprovincelocal as stateprovincelocal,
               rank_1.street2local as street2local,
               rank_1.streetlocal as streetlocal,
               rank_1.zippostalcodelocal as zippostalcodelocal,
               rank_1.accountgroup as accountgroup,
               rank_1.billingissue as billingissue,
               rank_1.accountstatus as accountstatus,
               rank_1.accountleadsourcetextfield as accountleadsourcetextfield,
               rank_1.active as active,
               rank_1.contactid as contactid,
               rank_1.customerpriority as customerpriority,
               rank_1.locationid as locationid,
               rank_1.numberoflocations as numberoflocations,
               rank_1.accountfax as accountfax,
               rank_1.accountnumber as accountnumber,
               rank_1.accountsite as accountsite,
               rank_1.accountnamelocal as accountnamelocal,
               rank_1.annualrevenue as annualrevenue,
               rank_1.preferredtechnician as preferredtechnician,
               rank_1.fieldsupportcountforautodispatch as fieldsupportcountforautodispatch,
               rank_1.productfamily as productfamily,
               rank_1.regulatorytype as regulatorytype,
               rank_1.legacysfdcrecordid as legacysfdcrecordid,
               rank_1.customersubtype as customersubtype,
               rank_1.isupdatedbysystem as isupdatedbysystem,
               rank_1.marketsegment as marketsegment,
               rank_1.populationgenomics as populationgenomics,
               rank_1.externalrecordid as externalrecordid,
               rank_1.primarymarketsegment as primarymarketsegment,
               rank_1.primarymarketsegmentpercentallocation as primarymarketsegmentpercentallocation,
               rank_1.channelprogramname as channelprogramname,
               rank_1.channelprogramlevelname as channelprogramlevelname,
               rank_1.accountcustomer_rank as accountcustomer_rank,
               rank_1.entityacquisitionid as entityacquisitionid,
               aggregation_1.agg_erpcustomerid as agg_erpcustomercount
          from rank_1
         inner join aggregation_1
            on rank_1.erpcustomerid = aggregation_1.erpcustomerid
       ),
       j_custaccount as (
        select j_custwithcustmerge.client as client,
               j_custwithcustmerge.customernumber as customernumber,
               j_custwithcustmerge.customername as customername,
               j_custwithcustmerge.title as title,
               j_custwithcustmerge.name1 as name1,
               j_custwithcustmerge.name2 as name2,
               j_custwithcustmerge.name3 as name3,
               j_custwithcustmerge.name4 as name4,
               j_custwithcustmerge.sortfield as sortfield,
               j_custwithcustmerge.housenumberandstreet as housenumberandstreet,
               j_custwithcustmerge.city as city,
               j_custwithcustmerge.district as district,
               j_custwithcustmerge.postalcode as postalcode,
               j_custwithcustmerge.pobox as pobox,
               j_custwithcustmerge.poboxpostalcode as poboxpostalcode,
               j_custwithcustmerge.countycode as countycode,
               j_custwithcustmerge.countycodedesc as countycodedesc,
               j_custwithcustmerge.region as region,
               j_custwithcustmerge.regionname as regionname,
               j_custwithcustmerge.countrykey as countrykey,
               j_custwithcustmerge.countryname as countryname,
               j_custwithcustmerge.firsttelephonenumber as firsttelephonenumber,
               j_custwithcustmerge.faxnumber as faxnumber,
               j_custwithcustmerge.address as address,
               j_custwithcustmerge.dateonwhichtherecordwascreated as dateonwhichtherecordwascreated,
               j_custwithcustmerge.nameofpersonwhocreatedtheobject as nameofpersonwhocreatedtheobject,
               j_custwithcustmerge.customeraccountgroup as customeraccountgroup,
               j_custwithcustmerge.customeraccountgroupdesc as customeraccountgroupdesc,
               j_custwithcustmerge.accountnumberofvendororcreditor as accountnumberofvendororcreditor,
               j_custwithcustmerge.citycoordinates as citycoordinates,
               j_custwithcustmerge.centraldeletionflagformasterrecord as centraldeletionflagformasterrecord,
               j_custwithcustmerge.taxnumber1 as taxnumber1,
               j_custwithcustmerge.taxnumber2 as taxnumber2,
               j_custwithcustmerge.vatregistrationnumber as vatregistrationnumber,
               j_custwithcustmerge.taxjurisdiction as taxjurisdiction,
               j_custwithcustmerge.uniformresourcelocator as uniformresourcelocator,
               j_custwithcustmerge.typeofbusiness as typeofbusiness,
               j_custwithcustmerge.groupidentifier as groupidentifier,
               j_custwithcustmerge.cms_winnercustomernumber as cms_winnercustomernumber,
               j_custwithcustmerge.cms_winnercustomercount as cms_winnercustomercount,
               join_1.accountid as sam_sfdcaccountid,
               join_1.accountname as sam_sfdcaccountname,
               join_1.accounttype as sam_sfdcaccounttype,
               join_1.recordname as sam_sfdcrecordname,
               join_1.recorddescription as sam_sfdcrecorddescription,
               join_1.parentid as sam_sfdcparentid,
               join_1.parentname as sam_sfdcparentname,
               join_1.industry as sam_sfdcindustry,
               join_1.ownerid as sam_sfdcownerid,
               join_1.ownername as sam_sfdcownername,
               join_1.partneraccount as sam_sfdcpartneraccount,
               join_1.accountsource as sam_sfdcaccountsource,
               join_1.excludefromterritoryassignmentrules as sam_sfdcexcludefromterritoryassignmentrules,
               join_1.creditblock as sam_sfdccreditblock,
               join_1.channelpartnertype as sam_sfdcchannelpartnertype,
               join_1.tier as sam_sfdctier,
               join_1.orderblock as sam_sfdcorderblock,
               join_1.salesblock as sam_sfdcsalesblock,
               join_1.addressstatus as sam_sfdcaddressstatus,
               join_1.resubmissionreason as sam_sfdcresubmissionreason,
               join_1.customertype as sam_sfdccustomertype,
               join_1.customersubtype as sam_sfdccustomersubtype,
               join_1.clinicaltype as sam_sfdcclinicaltype,
               join_1.accountgroup as sam_sfdcaccountgroup,
               join_1.accountstatus as sam_sfdcaccountstatus,
               join_1.productfamily as sam_sfdcproductfamily,
               join_1.regulatorytype as sam_sfdcregulatorytype,
               join_1.legacysfdcrecordid as sam_sfdclegacysfdcrecordid,
               join_1.populationgenomics as sam_sfdcpopulationgenomics,
               join_1.primarymarketsegment as sam_sfdcprimarymarketsegment,
               join_1.primarymarketsegmentpercentallocation as sam_sfdcprimarymarketsegmentpercentallocation,
               join_1.agg_erpcustomercount as calc_erpcustomeraccountcount,
               join_1.entityacquisitionid as sam_sfdcentityacquisitionid
          from j_custwithcustmerge
          left outer join join_1
            on j_custwithcustmerge.customernumber = join_1.erpcustomerid
       ),
       p_custhierrep as (
        select client,
               customernumber,
               customername as chr_customername,
               sourcesalesgroupingnumber as chr_sourcesalesgroupingnumber,
               sourcesalesgroupingname as chr_sourcesalesgroupingname,
               sourcenationalgroupingnumber as chr_sourcenationalgroupingnumber,
               sourcenationalgroupingname as chr_sourcenationalgroupingname,
               sourceglobalgroupingnumber as chr_sourceglobalgroupingnumber,
               sourceglobalgroupingname as chr_sourceglobalgroupingname,
               salesgroupingnumber as chr_salesgroupingnumber,
               salesgroupingname as chr_salesgroupingname,
               nationalgroupingnumber as chr_nationalgroupingnumber,
               nationalgroupingname as chr_nationalgroupingname,
               globalgroupingnumber as chr_globalgroupingnumber,
               globalgroupingname as chr_globalgroupingname,
               availablehierarchycount as chr_availablehierarchycount
          from {{ ref('BLV_ILMN_MDM_CUSTOMERHIERARCHYREPORTING_QV') }}
       ),
       j_custcustsales as (
        select j_custaccount.client as client,
               j_custaccount.customernumber as customernumber,
               j_custaccount.customername as customername,
               j_custaccount.title as title,
               j_custaccount.name1 as name1,
               j_custaccount.name2 as name2,
               j_custaccount.name3 as name3,
               j_custaccount.name4 as name4,
               j_custaccount.sortfield as sortfield,
               j_custaccount.housenumberandstreet as housenumberandstreet,
               j_custaccount.city as city,
               j_custaccount.district as district,
               j_custaccount.postalcode as postalcode,
               j_custaccount.pobox as pobox,
               j_custaccount.poboxpostalcode as poboxpostalcode,
               j_custaccount.countycode as countycode,
               j_custaccount.countycodedesc as countycodedesc,
               j_custaccount.region as region,
               j_custaccount.regionname as regionname,
               j_custaccount.countrykey as countrykey,
               j_custaccount.countryname as countryname,
               j_custaccount.firsttelephonenumber as firsttelephonenumber,
               j_custaccount.faxnumber as faxnumber,
               j_custaccount.address as address,
               j_custaccount.dateonwhichtherecordwascreated as dateonwhichtherecordwascreated,
               j_custaccount.nameofpersonwhocreatedtheobject as nameofpersonwhocreatedtheobject,
               j_custaccount.customeraccountgroup as customeraccountgroup,
               j_custaccount.customeraccountgroupdesc as customeraccountgroupdesc,
               j_custaccount.accountnumberofvendororcreditor as accountnumberofvendororcreditor,
               j_custaccount.citycoordinates as citycoordinates,
               j_custaccount.centraldeletionflagformasterrecord as centraldeletionflagformasterrecord,
               j_custaccount.taxnumber1 as taxnumber1,
               j_custaccount.taxnumber2 as taxnumber2,
               j_custaccount.vatregistrationnumber as vatregistrationnumber,
               j_custaccount.taxjurisdiction as taxjurisdiction,
               j_custaccount.uniformresourcelocator as uniformresourcelocator,
               j_custaccount.typeofbusiness as typeofbusiness,
               j_custaccount.groupidentifier as groupidentifier,
               j_custaccount.cms_winnercustomercount as cms_winnercustomercount,
               j_custaccount.cms_winnercustomernumber as cms_winnercustomernumber,
               j_custaccount.sam_sfdcaccountid as sam_sfdcaccountid,
               j_custaccount.sam_sfdcaccountname as sam_sfdcaccountname,
               j_custaccount.sam_sfdcaccounttype as sam_sfdcaccounttype,
               j_custaccount.sam_sfdcrecordname as sam_sfdcrecordname,
               j_custaccount.sam_sfdcrecorddescription as sam_sfdcrecorddescription,
               j_custaccount.sam_sfdcparentid as sam_sfdcparentid,
               j_custaccount.sam_sfdcparentname as sam_sfdcparentname,
               j_custaccount.sam_sfdcindustry as sam_sfdcindustry,
               j_custaccount.sam_sfdcownerid as sam_sfdcownerid,
               j_custaccount.sam_sfdcownername as sam_sfdcownername,
               j_custaccount.sam_sfdcpartneraccount as sam_sfdcpartneraccount,
               j_custaccount.sam_sfdcaccountsource as sam_sfdcaccountsource,
               j_custaccount.sam_sfdcexcludefromterritoryassignmentrules as sam_sfdcexcludefromterritoryassignmentrules,
               j_custaccount.sam_sfdccreditblock as sam_sfdccreditblock,
               j_custaccount.sam_sfdcchannelpartnertype as sam_sfdcchannelpartnertype,
               j_custaccount.sam_sfdctier as sam_sfdctier,
               j_custaccount.sam_sfdcorderblock as sam_sfdcorderblock,
               j_custaccount.sam_sfdcsalesblock as sam_sfdcsalesblock,
               j_custaccount.sam_sfdcaddressstatus as sam_sfdcaddressstatus,
               j_custaccount.sam_sfdcresubmissionreason as sam_sfdcresubmissionreason,
               j_custaccount.sam_sfdccustomertype as sam_sfdccustomertype,
               j_custaccount.sam_sfdccustomersubtype as sam_sfdccustomersubtype,
               j_custaccount.sam_sfdcclinicaltype as sam_sfdcclinicaltype,
               j_custaccount.sam_sfdcaccountgroup as sam_sfdcaccountgroup,
               j_custaccount.sam_sfdcaccountstatus as sam_sfdcaccountstatus,
               j_custaccount.sam_sfdcproductfamily as sam_sfdcproductfamily,
               j_custaccount.sam_sfdcregulatorytype as sam_sfdcregulatorytype,
               j_custaccount.sam_sfdclegacysfdcrecordid as sam_sfdclegacysfdcrecordid,
               j_custaccount.sam_sfdcpopulationgenomics as sam_sfdcpopulationgenomics,
               j_custaccount.sam_sfdcprimarymarketsegment as sam_sfdcprimarymarketsegment,
               j_custaccount.sam_sfdcprimarymarketsegmentpercentallocation as sam_sfdcprimarymarketsegmentpercentallocation,
               j_custaccount.calc_erpcustomeraccountcount as calc_erpcustomeraccountcount,
               j_custaccount.sam_sfdcentityacquisitionid as sam_sfdcentityacquisitionid,
               p_custhierrep.chr_sourcesalesgroupingnumber as chr_sourcesalesgroupingnumber,
               p_custhierrep.chr_sourcesalesgroupingname as chr_sourcesalesgroupingname,
               p_custhierrep.chr_sourcenationalgroupingnumber as chr_sourcenationalgroupingnumber,
               p_custhierrep.chr_sourcenationalgroupingname as chr_sourcenationalgroupingname,
               p_custhierrep.chr_sourceglobalgroupingnumber as chr_sourceglobalgroupingnumber,
               p_custhierrep.chr_sourceglobalgroupingname as chr_sourceglobalgroupingname,
               p_custhierrep.chr_salesgroupingnumber as chr_salesgroupingnumber,
               p_custhierrep.chr_salesgroupingname as chr_salesgroupingname,
               p_custhierrep.chr_nationalgroupingnumber as chr_nationalgroupingnumber,
               p_custhierrep.chr_nationalgroupingname as chr_nationalgroupingname,
               p_custhierrep.chr_globalgroupingnumber as chr_globalgroupingnumber,
               p_custhierrep.chr_globalgroupingname as chr_globalgroupingname,
               p_custhierrep.chr_availablehierarchycount as chr_availablehierarchycount,
               cast(iff((j_custaccount.cms_winnercustomercount is null),0,j_custaccount.cms_winnercustomercount) as INTEGER) as winnercustomercount,
               left(cast(iff(winnercustomercount = 1,j_custaccount.cms_winnercustomernumber,j_custaccount.customernumber) as NVARCHAR), 10) as winnercustomernumber
          from j_custaccount
          left outer join p_custhierrep
            on j_custaccount.client = p_custhierrep.client
           and j_custaccount.customernumber = p_custhierrep.customernumber
       ),
       projection_1 as (
        select client,
               customernumber,
               customername
          from {{ ref('BLV_MDM_SAPCUSTOMER_QV') }}
       ),
       join_2 as (
        select j_custcustsales.client as client,
               j_custcustsales.customernumber as customernumber,
               j_custcustsales.customername as customername,
               j_custcustsales.title as title,
               j_custcustsales.name1 as name1,
               j_custcustsales.name2 as name2,
               j_custcustsales.name3 as name3,
               j_custcustsales.name4 as name4,
               j_custcustsales.sortfield as sortfield,
               j_custcustsales.housenumberandstreet as housenumberandstreet,
               j_custcustsales.city as city,
               j_custcustsales.district as district,
               j_custcustsales.postalcode as postalcode,
               j_custcustsales.pobox as pobox,
               j_custcustsales.poboxpostalcode as poboxpostalcode,
               j_custcustsales.countycode as countycode,
               j_custcustsales.countycodedesc as countycodedesc,
               j_custcustsales.region as region,
               j_custcustsales.regionname as regionname,
               j_custcustsales.countrykey as countrykey,
               j_custcustsales.countryname as countryname,
               j_custcustsales.firsttelephonenumber as firsttelephonenumber,
               j_custcustsales.faxnumber as faxnumber,
               j_custcustsales.address as address,
               j_custcustsales.dateonwhichtherecordwascreated as dateonwhichtherecordwascreated,
               j_custcustsales.nameofpersonwhocreatedtheobject as nameofpersonwhocreatedtheobject,
               j_custcustsales.customeraccountgroup as customeraccountgroup,
               j_custcustsales.customeraccountgroupdesc as customeraccountgroupdesc,
               j_custcustsales.accountnumberofvendororcreditor as accountnumberofvendororcreditor,
               j_custcustsales.citycoordinates as citycoordinates,
               j_custcustsales.centraldeletionflagformasterrecord as centraldeletionflagformasterrecord,
               j_custcustsales.taxnumber1 as taxnumber1,
               j_custcustsales.taxnumber2 as taxnumber2,
               j_custcustsales.vatregistrationnumber as vatregistrationnumber,
               j_custcustsales.taxjurisdiction as taxjurisdiction,
               j_custcustsales.uniformresourcelocator as uniformresourcelocator,
               j_custcustsales.typeofbusiness as typeofbusiness,
               j_custcustsales.groupidentifier as groupidentifier,
               j_custcustsales.sam_sfdcaccountid as sfdcaccountid,
               j_custcustsales.calc_erpcustomeraccountcount as sfdcerpcustomeraccountcount,
               j_custcustsales.sam_sfdcaccountname as sfdcaccountname,
               j_custcustsales.sam_sfdcaccounttype as sfdcaccounttype,
               j_custcustsales.sam_sfdcrecordname as sfdcrecordname,
               j_custcustsales.sam_sfdcrecorddescription as sfdcrecorddescription,
               j_custcustsales.sam_sfdcparentid as sfdcparentid,
               j_custcustsales.sam_sfdcparentname as sfdcparentname,
               j_custcustsales.sam_sfdcindustry as sfdcindustry,
               j_custcustsales.sam_sfdcownerid as sfdcownerid,
               j_custcustsales.sam_sfdcownername as sfdcownername,
               j_custcustsales.sam_sfdcpartneraccount as sfdcpartneraccount,
               j_custcustsales.sam_sfdcaccountsource as sfdcaccountsource,
               j_custcustsales.sam_sfdcexcludefromterritoryassignmentrules as sfdcexcludefromterritoryassignmentrules,
               j_custcustsales.sam_sfdccreditblock as sfdccreditblock,
               j_custcustsales.sam_sfdcchannelpartnertype as sfdcchannelpartnertype,
               j_custcustsales.sam_sfdcorderblock as sfdcorderblock,
               j_custcustsales.sam_sfdcsalesblock as sfdcsalesblock,
               j_custcustsales.sam_sfdcaddressstatus as sfdcaddressstatus,
               j_custcustsales.sam_sfdcresubmissionreason as sfdcresubmissionreason,
               j_custcustsales.sam_sfdcaccountgroup as sfdcaccountgroup,
               j_custcustsales.sam_sfdcaccountstatus as sfdcaccountstatus,
               j_custcustsales.sam_sfdcproductfamily as sfdcproductfamily,
               j_custcustsales.sam_sfdcregulatorytype as sfdcregulatorytype,
               j_custcustsales.sam_sfdclegacysfdcrecordid as sfdclegacysfdcrecordid,
               j_custcustsales.sam_sfdcpopulationgenomics as sfdcpopulationgenomics,
               j_custcustsales.sam_sfdctier as sfdctier,
               j_custcustsales.sam_sfdccustomertype as sfdccustomertype,
               j_custcustsales.sam_sfdccustomersubtype as sfdccustomersubtype,
               j_custcustsales.sam_sfdcclinicaltype as sfdcclinicaltype,
               j_custcustsales.sam_sfdcprimarymarketsegment as sfdcprimarymarketsegment,
               j_custcustsales.sam_sfdcprimarymarketsegmentpercentallocation as sfdcprimarymarketsegmentpercentallocation,
               j_custcustsales.chr_sourcesalesgroupingnumber as sourcesalesgroupingnumber,
               j_custcustsales.chr_sourcesalesgroupingname as sourcesalesgroupingname,
               j_custcustsales.chr_sourcenationalgroupingnumber as sourcenationalgroupingnumber,
               j_custcustsales.chr_sourcenationalgroupingname as sourcenationalgroupingname,
               j_custcustsales.chr_sourceglobalgroupingnumber as sourceglobalgroupingnumber,
               j_custcustsales.chr_sourceglobalgroupingname as sourceglobalgroupingname,
               j_custcustsales.chr_salesgroupingnumber as salesgroupingnumber,
               j_custcustsales.chr_salesgroupingname as salesgroupingname,
               j_custcustsales.chr_nationalgroupingnumber as nationalgroupingnumber,
               j_custcustsales.chr_nationalgroupingname as nationalgroupingname,
               j_custcustsales.chr_globalgroupingnumber as globalgroupingnumber,
               j_custcustsales.chr_globalgroupingname as globalgroupingname,
               j_custcustsales.chr_availablehierarchycount as availablehierarchycount,
               j_custcustsales.winnercustomernumber as winnercustomernumber,
               j_custcustsales.winnercustomercount as winnercustomercount,
               j_custcustsales.sam_sfdcentityacquisitionid as sam_sfdcentityacquisitionid,
               projection_1.customername as calc_winnercustomername
          from j_custcustsales
          left outer join projection_1
            on j_custcustsales.client = projection_1.client
           and j_custcustsales.winnercustomernumber = projection_1.customernumber
       ) select client,
       customernumber,
       customername,
       title,
       name1,
       name2,
       name3,
       name4,
       sortfield,
       housenumberandstreet,
       city,
       district,
       postalcode,
       pobox,
       poboxpostalcode,
       countycode,
       countycodedesc,
       region,
       regionname,
       countrykey,
       countryname,
       firsttelephonenumber,
       faxnumber,
       address,
       dateonwhichtherecordwascreated,
       nameofpersonwhocreatedtheobject,
       customeraccountgroup,
       customeraccountgroupdesc,
       accountnumberofvendororcreditor,
       citycoordinates,
       centraldeletionflagformasterrecord,
       taxnumber1,
       taxnumber2,
       vatregistrationnumber,
       taxjurisdiction,
       uniformresourcelocator,
       typeofbusiness,
       groupidentifier,
       sfdcaccountid,
       sfdcerpcustomeraccountcount,
       sfdcaccountname,
       sfdcaccounttype,
       sfdcrecordname,
       sfdcrecorddescription,
       sfdcparentid,
       sfdcparentname,
       sfdcindustry,
       sfdcownerid,
       sfdcownername,
       sfdcpartneraccount,
       sfdcaccountsource,
       sfdcexcludefromterritoryassignmentrules,
       sfdccreditblock,
       sfdcchannelpartnertype,
       sfdcorderblock,
       sfdcsalesblock,
       sfdcaddressstatus,
       sfdcresubmissionreason,
       sfdcaccountgroup,
       sfdcaccountstatus,
       sfdcproductfamily,
       sfdcregulatorytype,
       sfdclegacysfdcrecordid,
       sfdcpopulationgenomics,
       sfdctier,
       sfdccustomertype,
       sfdccustomersubtype,
       sfdcclinicaltype,
       sfdcprimarymarketsegment,
       sfdcprimarymarketsegmentpercentallocation,
       sourcesalesgroupingnumber,
       sourcesalesgroupingname,
       sourcenationalgroupingnumber,
       sourcenationalgroupingname,
       sourceglobalgroupingnumber,
       sourceglobalgroupingname,
       salesgroupingnumber,
       salesgroupingname,
       nationalgroupingnumber,
       nationalgroupingname,
       globalgroupingnumber,
       globalgroupingname,
       availablehierarchycount,
       winnercustomernumber,
       calc_winnercustomername as winnercustomername,
       winnercustomercount,
       'Placholder' as globalregion,
       'Placeholder' as globalregionname,
       sam_sfdcentityacquisitionid as sfdcentityacquisitionid
  from join_2